[package]
name = "frogment"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
